SDKSTAGE=/home/davilla/amlogic/buildroot-2010.05/output/staging
XBMCPREFIX=/opt/xbmc-aml
TARGETFS=/home/davilla/amlogic/buildroot-2010.05/output/target
TOOLCHAIN=/opt/arm-2010q1
BUILDROOT=/home/davilla/amlogic/buildroot-2010.05
BASE_URL=http://mirrors.xbmc.org/build-deps/darwin-libs
TARBALLS_LOCATION=/opt/xbmc-tarballs
RETRIEVE_TOOL=/usr/bin/curl
RETRIEVE_TOOL_FLAGS=-Ls --create-dirs --output $(TARBALLS_LOCATION)/$(ARCHIVE)
ARCHIVE_TOOL=PATH=/bin /bin/tar
ARCHIVE_TOOL_FLAGS=xf
JOBS=1
